### ISSUE TITLE
getting a crash when specifying --high or --low

### ISSUE THREAD

**Issue by stillnet** [keenerd/rtl-sdr-misc#14]
I'm trying to trim out the amount of data displayed using --high and/or --low, but whenever I specify either one I get an error.

Example:
`root@DietPi:/tmp# heatmap.py --low 146000000 --high 147000000 2m.csv /var/www/html/2m.png
loading
Traceback (most recent call last):
  File "/usr/bin/heatmap.py", line 615, in <module>
    summarize_pass(args)
  File "/usr/bin/heatmap.py", line 261, in summarize_pass
    start_col, stop_col = slice_columns(columns, args.low_freq, args.high_freq)
  File "/usr/bin/heatmap.py", line 223, in slice_columns
    if low_freq  is not None and low <= low_freq  <= high:
NameError: global name 'low' is not defined
`

**Comment by HHsty** [comment]
I believe this is redundant issue , check : https://github.com/keenerd/rtl-sdr-misc/issues/11

**Comment by stillnet** [comment]
Yep, I'll close this one.
