### ISSUE TITLE
heatmap for a audio wav file

### ISSUE THREAD

**Issue by pauledd** [keenerd/rtl-sdr-misc#18]
Hi there
this is not an issue but more a question.
Is it somehow possible to analyse audio files previously recorded and feed heatmap.py with it, 
or is anyone aware how I could do this with other tools? (linux prefered )

Background is: I want to do a long record audio session my environment during night, 6 hours or so to a raw audio file and I would like to plot/heatmap that file like heatmap it does.
The reason is there is some kind of annoying audible background hum at ~49Hz in my area and I want
to analyse that further.

**Comment by sm3ulc** [comment]
Try sox ability to generate spectrogram.

// David

Den 8 dec. 2017 18:27 skrev "pauledd" <notifications@github.com>:

**Comment by pauledd** [comment]
Thank you,I'll try that. I also found "sonic-visualiser" for linux but that might not be perfect for big files...
